name: flutter_chat
description: A flutter chat project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  json_annotation: ^4.6.0
  rxdart: ^0.27.5
  connectivity_plus: ^2.3.9
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dartz: ^0.10.1
  responsive_framework: ^0.2.0
  scrollable_positioned_list: ^0.3.5
  riverpod: ^2.3.0
  flutter_riverpod: ^2.1.1
  firebase_core: ^2.4.0
  flutter_svg: ^1.0.3
  formz: ^0.4.1
  image_picker: ^0.8.6
  firebase_auth: ^4.2.5
  firebase_database: ^10.0.9
  equatable: ^2.0.5
  firebase_storage: ^11.0.10
  cloud_firestore: ^4.3.1
  google_sign_in: ^6.0.1
  shared_preferences: ^2.0.18
  freezed_annotation: ^2.2.0
  flutter_facebook_auth: ^5.0.8

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.3.1

dependency_overrides:
  intl: ^0.17.0


flutter:

  assets:
    - resources/assets/icons/

  uses-material-design: true
flutter_intl:
  enabled: true